/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-12-01 15:17:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>MTS Home</title>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.3/fullcalendar.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.3/fullcalendar.min.css\"/>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#input_week\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#input_monthly\").hide();\r\n");
      out.write("\t\t\t$(\"#input_weekly\").show();\r\n");
      out.write("\t\t\t$(\"#weekly\").fullCalendar('destroy');\r\n");
      out.write("\t\t      $(\"#monthly\").fullCalendar('destroy');\r\n");
      out.write("\t\t    $(\"#weekly\").fullCalendar({\r\n");
      out.write("\t\t    \theader: {\r\n");
      out.write("\t\t        \tleft: 'prev,next today',\r\n");
      out.write("\t\t        \tcenter: 'title',\r\n");
      out.write("\t\t        \tright: ''\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        defaultView: 'basicWeek',\r\n");
      out.write("\t\t        height: 150,\r\n");
      out.write("\t\t        dayClick: function(date, jsEvent, view) {\r\n");
      out.write("\t\t        \t$(\".fc-day\").removeClass(\"selected\");\r\n");
      out.write("\t\t        \t$(\"#input_field\").html(\"Worked Hours: <input id='input_tag' name='worked_hour' type='text'></div>\");\r\n");
      out.write("\t\t        \t$(\"#input_field\").prepend(\"<div>Please input hours worked for <div id='detail_date'>\"+date.format()+\"</div></div>\");\r\n");
      out.write("\t\t        \tvar hour_in_target_date = $(\"#hour_in_\"+date.format()).html();\r\n");
      out.write("\t\t        \tif(hour_in_target_date != undefined) {\r\n");
      out.write("\t\t          \t\t$(\"#input_tag\").val(hour_in_target_date);\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        \t$.ajax({\r\n");
      out.write("\t\t      \t\t\turl: \"showRecord.html\",\r\n");
      out.write("\t\t      \t\t\ttype: \"post\",\r\n");
      out.write("\t\t      \t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t      \t\t\tdata: {date: date.format()},\r\n");
      out.write("\t\t      \t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t      \t\t\t\tvar workHour = $(data).find(\"workHours\").text();\r\n");
      out.write("\t\t      \t\t    \tvar ptoHour = $(data).find(\"ptoHours\").text();\r\n");
      out.write("\t\t      \t\t    \tvar otHour = $(data).find(\"otHours\").text();\r\n");
      out.write("\t\t      \t\t    \t$(\"#input_field\").prepend(\"<div>Worked hours: \"+workHour+\"</div><div>Used PTO: \"+ptoHour+\"</div><div>OT hours Earned: \"+otHour+\"</div>\");\r\n");
      out.write("\t\t      \t\t\t}\r\n");
      out.write("\t\t      \t\t});\r\n");
      out.write("\t\t            // change the day's background color just for fun\r\n");
      out.write("\t\t        \t$(this).addClass(\"selected\");\r\n");
      out.write("\t\t        \t$(\"#input_tag\").on(\"blur\", function() {\r\n");
      out.write("\t\t            \tvar hours = $(\"#input_tag\").val();\r\n");
      out.write("\t\t            \tvar detail_date = $(\"#detail_date\").text();\r\n");
      out.write("\t\t            \t$(\"td[data-date='\"+detail_date+\"']\").html(\"Worked Hours: <div id='hour_in_\"+detail_date+\"'>\"+hours+\"</div>\");\r\n");
      out.write("\t\t          \t});\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    $(\".fc-day\").html(\"Worked Hours: \");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#input_month\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#input_weekly\").hide();\r\n");
      out.write("\t\t    $(\"#input_monthly\").show();\r\n");
      out.write("\t\t    $(\"#weekly\").fullCalendar('destroy');\r\n");
      out.write("\t\t    $(\"#monthly\").fullCalendar('destroy');\r\n");
      out.write("\t\t    $(\"#monthly\").fullCalendar({\r\n");
      out.write("\t\t    \theader: {\r\n");
      out.write("\t\t        \tleft: 'prev,next today',\r\n");
      out.write("\t\t        \tcenter: 'title',\r\n");
      out.write("\t\t        \tright: ''\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        height: 500,\r\n");
      out.write("\t\t        dayClick: function(date, jsEvent, view) {\r\n");
      out.write("\t\t        \t$(\".fc-day\").removeClass(\"selected\");\r\n");
      out.write("\t\t        \t$(\"#input_mon_field\").html(\"Worked Hours: <input id='input_mon_tag' name='worked_hour' type='text'></div>\");\r\n");
      out.write("\t\t            $(\"#input_mon_field\").prepend(\"<div>Please input hours worked for <div id='detail_mon_date'>\"+date.format()+\"</div></div>\");\r\n");
      out.write("\t\t            var hour_in_target_date = $(\"#hour_in_mon_\"+date.format()).html();\r\n");
      out.write("\t\t            if(hour_in_target_date != undefined) {\r\n");
      out.write("\t\t          \t\t$(\"#input_mon_tag\").val(hour_in_target_date);\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            $.ajax({\r\n");
      out.write("\t\t      \t\t\turl: \"showRecord.html\",\r\n");
      out.write("\t\t      \t\t\ttype: \"post\",\r\n");
      out.write("\t\t      \t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t      \t\t\tdata: {date:date.format()},\r\n");
      out.write("\t\t      \t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t      \t\t\t\tvar workHour = $(data).find(\"workHours\").text();\r\n");
      out.write("\t\t      \t\t        var ptoHour = $(data).find(\"ptoHours\").text();\r\n");
      out.write("\t\t      \t\t        var otHour = $(data).find(\"otHours\").text();\r\n");
      out.write("\t\t      \t\t        $(\"#input_mon_field\").prepend(\"<div>Worked hours: \"+workHour+\"</div><div>Used PTO: \"+ptoHour+\"</div><div>OT hours Earned: \"+otHour+\"</div>\");\r\n");
      out.write("\t\t      \t\t\t}\r\n");
      out.write("\t\t      \t    });\r\n");
      out.write("\t\t          // change the day's background color just for fun\r\n");
      out.write("\t\t            $(this).addClass(\"selected\");\r\n");
      out.write("\t\t            $(\"#input_mon_tag\").on(\"blur\", function() {\r\n");
      out.write("\t\t            \tvar hours = $(\"#input_mon_tag\").val();\r\n");
      out.write("\t\t            \tvar detail_date = $(\"#detail_mon_date\").text();\r\n");
      out.write("\t\t            \t$(\"td.fc-day[data-date='\"+detail_date+\"']\").html(\"<br/><br/>Work Hour: <div id='hour_in_mon_\"+detail_date+\"'>\"+hours+\"</div>\");\r\n");
      out.write("\t\t            });\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    $(\".fc-day\").html(\"<br/><br/>Work Hour: \");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#submit_mon_form\").on(\"click\", function() {\r\n");
      out.write("\t\t\tvar myArray = [];\r\n");
      out.write("\t\t    $(\".fc-day\").each(function() {\r\n");
      out.write("\t\t    \tvar txt = $(this).text();\r\n");
      out.write("\t\t        var date = $(this).attr(\"data-date\");\r\n");
      out.write("\t\t        var time = $(this).find(\"#hour_in_mon_\"+date).text();\r\n");
      out.write("\t\t        myArray.push(time);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    alert(myArray);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#submit_form\").on(\"click\", function() {\r\n");
      out.write("\t\t    var myArray = [];\r\n");
      out.write("\t\t    $(\".fc-day\").each(function() {\r\n");
      out.write("\t\t    \tvar txt = $(this).text();\r\n");
      out.write("\t\t        var date = $(this).attr(\"data-date\");\r\n");
      out.write("\t\t        var time = $(this).find(\"#hour_in_\"+date).text();\r\n");
      out.write("\t\t        myArray.push(time);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    alert(myArray);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.fc_day {\r\n");
      out.write("\t\tz-index: -1\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.hour_input {\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t.selected {\r\n");
      out.write("\t\tbackground-color: #C0C0C0;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"reporting.html\">See Timesheet Report</a>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">Logout</a>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<table id=\"userInfo\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>First Name: </td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.fn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Last Name: </td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.ln}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Consultant Name: </td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.cn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<button id=\"input_week\">input by week</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<button id=\"input_month\">input by month</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>input by month</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"input_weekly\" style=\"display: none\">\r\n");
      out.write("\t<div id=\"weekly\" style=\"width: 70%; height: 30%\"></div>\r\n");
      out.write("\t<div id=\"input_field\" style=\"width: 30%; height: 30%\"></div>\r\n");
      out.write("\t<button id=\"submit_form\">Submit</button>\t\t\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"input_monthly\" style=\"display: none\">\r\n");
      out.write("\t<div id=\"monthly\" style=\"width: 70%; height: 30%\"></div>\r\n");
      out.write("\t<div id=\"input_mon_field\" style=\"width: 30%; height: 30%\"></div>\r\n");
      out.write("\t<button id=\"submit_mon_form\">Submit</button>\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/pages/home.jsp(148,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/j_spring_security_logout");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
