/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-11-29 20:04:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#empno\").on(\"blur\", function() {\r\n");
      out.write("\t\t\t$(\"#empnoValid\").hide();\r\n");
      out.write("\t\t\t$(\"#empnoNo\").hide();\r\n");
      out.write("\t\t\t$(\"#empnoExist\").hide();\r\n");
      out.write("\t\t\t$(\".registerInfo\").hide();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"validation/emp.html\",\r\n");
      out.write("\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\t\tdata: {empno: $(\"#empno\").val()},\r\n");
      out.write("\t\t\t\tsuccess: function(response) {\r\n");
      out.write("\t\t\t\t\tvar result = response.toString().trim();\r\n");
      out.write("\t\t\t\t\tif (result==\"valid\") {\r\n");
      out.write("\t\t\t\t\t\t$(\".registerInfo\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if (result==\"empty\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#empnoValid\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if (result==\"no\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#empnoNo\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if (result==\"exist\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#empnoExist\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(msg) {\r\n");
      out.write("\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#username\").on(\"blur\", function() {\r\n");
      out.write("\t\t\t$(\"#usernameValid\").hide();\r\n");
      out.write("\t\t\t$(\"#usernameAva\").hide();\r\n");
      out.write("\t\t\t$(\"#usernameExist\").hide();\r\n");
      out.write("\t\t\t$(\"#usernameReq\").hide();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"validation/username.html\",\r\n");
      out.write("\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\t\tdata: {username: $(\"#username\").val()},\r\n");
      out.write("\t\t\t\tsuccess: function(response) {\r\n");
      out.write("\t\t\t\t\tvar result = response.toString().trim();\r\n");
      out.write("\t\t\t\t\tif (result==\"empty\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#usernameValid\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if (result==\"success\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#usernameAva\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t$(\"#usernameExist\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(msg) {\r\n");
      out.write("\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#submit\").on(\"click\", validateForm);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateForm() {\r\n");
      out.write("\t\t$(\"#usernameReq\").hide();\r\n");
      out.write("\t\t$(\"#passwordReq\").hide();\r\n");
      out.write("\t\t$(\"#emailReq\").hide();\r\n");
      out.write("\t\tif($(\"#username\").val().length==0) {\r\n");
      out.write("\t\t\t$(\"#usernameReq\").show();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#password\").val().length==0) {\r\n");
      out.write("\t\t\t$(\"#passwordReq\").show();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#email\").val().length==0) {\r\n");
      out.write("\t\t\t$(\"#emailReq\").show();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.alert {\r\n");
      out.write("\t\tcolor: red;\r\n");
      out.write("\t\tline-height: 16px;\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tmargin: 10;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"registerForm\" action=\"registered.html\" method=\"post\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Employee No.:</td>\r\n");
      out.write("\t\t\t<td><input id=\"empno\" type=\"text\" name=\"empno\"/></td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"empnoValid\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tInvalid employee number\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"empnoExist\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tAccount already exists for this employee number\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"empnoNo\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tNo such employee number\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"registerInfo\" style=\"display:none\">\r\n");
      out.write("\t\t\t<td>Username:</td>\r\n");
      out.write("\t\t\t<td><input id=\"username\" type=\"text\" name=\"username\" required/></td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"usernameValid\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tInvalid username\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"usernameExist\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tUsername already exists\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"usernameReq\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tUsername is required\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td id=\"usernameAva\" style=\"display:none; color:green\">\r\n");
      out.write("\t\t\t\tAvailable\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"registerInfo\" style=\"display:none\">\r\n");
      out.write("\t\t\t<td>Password:</td>\r\n");
      out.write("\t\t\t<td><input id=\"password\" type=\"password\" name=\"password\" required/></td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"passwordReq\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tPassword is required\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"registerInfo\" style=\"display:none\">\r\n");
      out.write("\t\t\t<td>Email:</td>\r\n");
      out.write("\t\t\t<td><input id=\"email\" type=\"email\" name=\"email\" required/></td>\r\n");
      out.write("\t\t\t<td class=\"alert\" id=\"emailReq\" style=\"display:none\">\r\n");
      out.write("\t\t\t\tEmail is required\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"registerInfo\" style=\"display:none\">\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input id=\"clear\" type=\"reset\" value=\"Clear\"/>\r\n");
      out.write("\t\t\t\t<input id=\"submit\" type=\"submit\" value=\"Submit\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
