/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-12-01 15:18:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reporting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Reporting</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\"/>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#seeHoursInfo\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#seeHoursInfo\").hide();\r\n");
      out.write("\t\t\t$(\"#hideHoursInfo\").show();\r\n");
      out.write("\t\t\t$(\"#hoursInfo\").hide();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"hoursInfo.html\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\t\tsuccess: showHours,\r\n");
      out.write("\t\t\t\terror: function() {\r\n");
      out.write("\t\t\t\t\talert(\"failed!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#hideHoursInfo\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#hoursInfo\").hide();\r\n");
      out.write("\t\t\t$(\"#hideHoursInfo\").hide();\r\n");
      out.write("\t\t\t$(\"#seeHoursInfo\").show();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#dateButton\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#recordInfo\").hide();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"showRecord.html\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\t\tdata: {date: $(\"#selectDate\").val()},\r\n");
      out.write("\t\t\t\tsuccess: showRecord,\r\n");
      out.write("\t\t\t\terror: function() {\r\n");
      out.write("\t\t\t\t\talert(\"failed!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#periodButton\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").hide();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"showTimesheet.html\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdataType: \"xml\",\r\n");
      out.write("\t\t\t\tdata: {startDate: $(\"#startDate\").val(),\r\n");
      out.write("\t\t\t\t\t   endDate: $(\"#endDate\").val()},\r\n");
      out.write("\t\t\t\tsuccess: showTimesheet,\r\n");
      out.write("\t\t\t\terror: function() {\r\n");
      out.write("\t\t\t\t\talert(\"failed!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction showHours(data) {\r\n");
      out.write("\t\t$(\"#remainpto\").text($(data).find(\"remainpto\").text());\r\n");
      out.write("\t\t$(\"#usedpto\").text($(data).find(\"usedpto\").text());\r\n");
      out.write("\t\t$(\"#earnedot\").text($(data).find(\"ot\").text());\r\n");
      out.write("\t\t$(\"#hoursInfo\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showRecord(data) {\r\n");
      out.write("\t\t$(\"#recordNoRecord\").html(\"\");\r\n");
      out.write("\t\t$(\"#recordEntries\").empty();\r\n");
      out.write("\t\tif ($(data).length==0) {\r\n");
      out.write("\t\t\t$(\"#recordNoRecord\").html(\"No record for this date.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tvar date = $(data).find(\"workDate\").text();\r\n");
      out.write("\t\t\t$(\"#recordEntries\").append(\"<td>\"+date+\"</td\");\r\n");
      out.write("\t\t\tvar workHours = $(data).find(\"workHours\").text();\r\n");
      out.write("\t\t\t$(\"#recordEntries\").append(\"<td>\"+workHours+\"</td\");\r\n");
      out.write("\t\t\tvar ptoHours = $(data).find(\"ptoHours\").text();\r\n");
      out.write("\t\t\t$(\"#recordEntries\").append(\"<td>\"+ptoHours+\"</td\");\r\n");
      out.write("\t\t\tvar otHours = $(data).find(\"otHours\").text();\r\n");
      out.write("\t\t\t$(\"#recordEntries\").append(\"<td>\"+otHours+\"</td\");\t\r\n");
      out.write("\t\t\t$(\"#recordInfo\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showTimesheet(data) {\r\n");
      out.write("\t\t$(\"#timesheetNoRecord\").html(\"\");\r\n");
      out.write("\t\t$(\"#timesheetInfo\").empty();\r\n");
      out.write("\t\tvar val=$(\"input.option:radio[name='showOption']:checked\").val();\r\n");
      out.write("\t\tif ($(data).length==0) {\r\n");
      out.write("\t\t\t$(\"#timesheetNoRecord\").html(\"No record for this period.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (val==\"showAll\") {\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").append(\"<tr><th>Date</th>\"+\"<th>Worked Hours</th>\"+\r\n");
      out.write("\t\t\t\"<th>Used PTO Hours</th><th>OT Earned</th></tr>\");\r\n");
      out.write("\t\t\t$(data).find(\"record\").each(function() {\r\n");
      out.write("\t\t\t\tvar row = \"<tr>\";\r\n");
      out.write("\t\t\t\tvar date = $(this).find(\"workDate\").text();\r\n");
      out.write("\t\t\t\trow = row + \"<td>\" + date + \"</td>\";\r\n");
      out.write("\t\t\t\tvar workHours = $(this).find(\"workHours\").text();\r\n");
      out.write("\t\t\t\trow = row + \"<td>\" + workHours + \"</td>\";\r\n");
      out.write("\t\t\t\tvar ptoHours = $(this).find(\"ptoHours\").text();\r\n");
      out.write("\t\t\t\trow = row + \"<td>\" + ptoHours + \"</td>\";\r\n");
      out.write("\t\t\t\tvar otHours = $(this).find(\"otHours\").text();\r\n");
      out.write("\t\t\t\trow = row + \"<td>\" + otHours + \"</td>\";\r\n");
      out.write("\t\t\t\trow = row + \"</tr>\";\r\n");
      out.write("\t\t\t\t$(\"#timesheetInfo\").append(row);\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (val==\"showPto\") {\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").append(\"<tr><th>Date</th><th>Used PTO Hours</th>\");\r\n");
      out.write("\t\t\t$(data).find(\"record\").each(function() {\r\n");
      out.write("\t\t\t\tvar ptoHours = $(this).find(\"ptoHours\").text();\r\n");
      out.write("\t\t\t\tif (ptoHours!=0) {\r\n");
      out.write("\t\t\t\t\tvar row = \"<tr>\";\r\n");
      out.write("\t\t\t\t\tvar date = $(this).find(\"workDate\").text();\r\n");
      out.write("\t\t\t\t\trow = row + \"<td>\" + date + \"</td>\";\r\n");
      out.write("\t\t\t\t\trow = row + \"<td>\" + ptoHours + \"</td>\";\r\n");
      out.write("\t\t\t\t\t$(\"#timesheetInfo\").append(row);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (val==\"showOt\") {\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").append(\"<tr><th>Date</th><th>OT Earned</th>\");\r\n");
      out.write("\t\t\t$(data).find(\"record\").each(function() {\r\n");
      out.write("\t\t\t\tvar otHours = $(this).find(\"otHours\").text();\r\n");
      out.write("\t\t\t\tif (otHours!=0) {\r\n");
      out.write("\t\t\t\t\tvar row = \"<tr>\";\r\n");
      out.write("\t\t\t\t\tvar date = $(this).find(\"workDate\").text();\r\n");
      out.write("\t\t\t\t\trow = row + \"<td>\" + date + \"</td>\";\r\n");
      out.write("\t\t\t\t\trow = row + \"<td>\" + otHours + \"</td>\";\r\n");
      out.write("\t\t\t\t\t$(\"#timesheetInfo\").append(row);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (val==\"showPaid\") {\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").append(\"<tr><th>Date</th><th>Paid Hours</th>\");\r\n");
      out.write("\t\t\t$(data).find(\"record\").each(function() {\r\n");
      out.write("\t\t\t\tvar row = \"<tr>\";\r\n");
      out.write("\t\t\t\tvar date = $(this).find(\"workDate\").text();\r\n");
      out.write("\t\t\t\trow = row + \"<td>\" + date + \"</td>\";\r\n");
      out.write("\t\t\t\tvar workHours = Number($(this).find(\"workHours\").text());\r\n");
      out.write("\t\t\t\tvar ptoHours = Number($(this).find(\"ptoHours\").text());\r\n");
      out.write("\t\t\t\tvar paidHours = workHours + ptoHours;\r\n");
      out.write("\t\t\t\trow = row + \"<td>\" + paidHours + \"</td>\";\r\n");
      out.write("\t\t\t\t$(\"#timesheetInfo\").append(row);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#timesheetInfo\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\ttable,th,td {\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t}\r\n");
      out.write("\tth, td {\r\n");
      out.write("    \tpadding: 5px;\r\n");
      out.write("    \ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable#timesheetInfo tr:nth-child(even) {\r\n");
      out.write("    \tbackground-color: #eee;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable#timesheetInfo tr:nth-child(odd) {\r\n");
      out.write("   \t\tbackground-color:#fff;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable#timesheetInfo th\t{\r\n");
      out.write("    \tbackground-color: black;\r\n");
      out.write("    \tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"main.html\">Go back to input page</a>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">Logout</a>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<button type=\"button\" id=\"seeHoursInfo\">Show PTO and OT</button>\r\n");
      out.write("<button type=\"button\" id=\"hideHoursInfo\" style=\"display:none\">Hide PTO and OT</button>\r\n");
      out.write("<table id=\"hoursInfo\" style=\"display:none\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Remaining PTO</td>\r\n");
      out.write("\t\t<td id=\"remainpto\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Used PTO</td>\r\n");
      out.write("\t\t<td id=\"usedpto\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Earned OT</td>\r\n");
      out.write("\t\t<td id=\"earnedot\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<p>Timesheet for a specific date:</p>\r\n");
      out.write("<p>Select date: <input id=\"selectDate\" type=\"date\" name=\"date\"/>\r\n");
      out.write("<button type=\"button\" id=\"dateButton\">Submit</button>\r\n");
      out.write("</p>\r\n");
      out.write("<p id=\"recordNoRecord\"></p>\r\n");
      out.write("<table id=\"recordInfo\" style=\"display:none\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th id=\"workDate\">Date</th>\r\n");
      out.write("\t\t<th id=\"workHours\">Worked Hours</th>\r\n");
      out.write("\t\t<th id=\"ptoUsage\">Used PTO Hours</th>\r\n");
      out.write("\t\t<th id=\"ot\">OT Earned</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr id=\"recordEntries\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<p>Timesheet for a period of time:</p>\r\n");
      out.write("<p>Start date: <input id=\"startDate\" type=\"date\" name=\"startDate\"/>\r\n");
      out.write("End date: <input id=\"endDate\" type=\"date\" name=\"endDate\"/>\r\n");
      out.write("</p>\r\n");
      out.write("<p>\r\n");
      out.write("<input class=\"option\" type=\"radio\" name=\"showOption\" value=\"showAll\" checked/>Show All\r\n");
      out.write("<input class=\"option\" type=\"radio\" name=\"showOption\" value=\"showPto\"/>Show PTO Used\r\n");
      out.write("<input class=\"option\" type=\"radio\" name=\"showOption\" value=\"showOt\"/>Show OT Earned\r\n");
      out.write("<input class=\"option\" type=\"radio\" name=\"showOption\" value=\"showPaid\"/>Show Paid Hours\r\n");
      out.write("</p>\r\n");
      out.write("<p>\r\n");
      out.write("<button type=\"button\" id=\"periodButton\">Submit</button>\r\n");
      out.write("</p>\r\n");
      out.write("<p id=\"timesheetNoRecord\"></p>\r\n");
      out.write("<table id=\"timesheetInfo\" style=\"display:none\">\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/pages/reporting.jsp(179,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/j_spring_security_logout");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
